blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, create_comment


app_name='blog'

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('detail/<str:pk>', BlogDetailView.as_view(), name="detail"),
    path('comment', create_comment, name='comment'),
]

manager/urls.py
from django.urls import path
from .views import *


app_name = 'manager'

urlpatterns = [
    path('', ManagerHomeView.as_view(), name='home'),
    path('home_sliders', HomeSliderListView.as_view(), name='home_sliders'),
    path('tag_list', TagListView.as_view(), name='tag_list'),
    path('delete-tag/<str:pk>', DeleteTagView.as_view(), name='delete_tag'),
    path('product-list', ProductListView.as_view(), name='product_list'),
    path('product-update/<str:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('delete-product/<str:pk>', DeleteProductView.as_view(), name='delete_product'),
    path('category-list', CategoryListView.as_view(), name='category_list'),
    path('delete-category/<str:pk>', DeleteCategoryView.as_view(), name='delete_category'),
    path('our_products_are', OurProductsAreView.as_view(), name='our_products_are'),
    path('delivery-team-list', delivery_team_list, name='delivery_team_list'),
    path('delete-delivery-team/<str:pk>', DeleteDeliveryTeamView.as_view(), name='delete_delivery_team'),
    path('supplier-list', supplier_list, name='supplier_list'),
    path('supplier-waiting-list', SupplierFormView.as_view(), name='supplier_waiting_list'),
    path('supplier-waiting-update/<str:pk>', SupplierFormUpdateView.as_view(), name='supplier_waiting_update'),
    path('update-supplier/<str:pk>', SupplierUpdateView.as_view(), name='supplier_update'),
    path('delete-supplier/<str:pk>', DeleteSupplierView.as_view(), name='delete_supplier'),
    path('blog-create', BlogCreateView.as_view(), name='blog_create'),
    path('blog-update/<str:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog-delete/<str:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    path('settings', ManagerSettingView.as_view(), name='settings'),

    path('campaigns', CampaignView.as_view(), name='campaign'),
    path('campaign/<int:pk>/update', CampaignUpdateView.as_view(), name='campaign_update'),
    path('campaign/<int:pk>/delete', CampaignDeleteView.as_view(), name='campaign_delete'),

    path('product_images', ProductImageView.as_view(), name='product_images'),
    path('product_image/<int:pk>/update', ProductImageUpdateView.as_view(), name='product_image_update'),
    path('product_image/<int:pk>/delete', ProductImageDeleteView.as_view(), name='product_image_delete'),
]

manager/models.py
from django.db import models
from django.contrib.auth import get_user_model
from datetime import date
from PIL import Image
from seller.validators import phone_validation

# Create your models here.

USER = get_user_model()

def get_image_path(instance, filename):
    name = instance.username
    return f'manager/{name}/{filename}'


class Manager(models.Model):
    user = models.OneToOneField(USER, on_delete=models.CASCADE)
    username = models.CharField(max_length=100)
    phone_num = models.CharField(max_length=10, validators=[phone_validation])
    profile_pic = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)


    def __str__(self):
        return self.user.email

    @property
    def calculate_age(self):
        age = date.today().year - self.dob.year 
        return age 

    @property
    def imageURL(self):
        try:
            url = self.profile_pic.url
        except:
            url = ''
        return url

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try: 
            image = Image.open(self.profile_pic.path)
            if (image.height>300 and image.width>300):
                output_size = (300, 300)
                image.thumbnail(output_size)
                image.save(self.profile_pic.path)  
        except:
            url = ''  


#Model for Home Main Slider 
def get_slider_path(instance, filename):
    name = instance.title
    return f'home_main_slider/{name}/{filename}'

class HomeTopSlider(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to=get_slider_path)
    detail = models.TextField()

    def __str__(self):
        return f'Slider of {self.title}'

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url    


#Model for Our Products Are Section 
def get_product_info_path(instance, filename):
    name = instance.info
    return f'our_product_are/{name}/{filename}'

class OurProductsAre(models.Model):
    image = models.ImageField(upload_to=get_product_info_path)
    info = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.info}'

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

manager/views.py
from django.shortcuts import render, redirect
from .models import Manager, HomeTopSlider, OurProductsAre

from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from product.forms import ProductCreateForm
from delivery_team.forms import DeliveryTeamRegisterForm
from seller.forms import SupplierRegisterForm

from product.models import Tag,Product, Category, Campaign, ProductImage
from delivery_team.models import DeliveryTeamProfile
from seller.models import SupplierProfile, SupplierForm
from blog.models import BlogModel

from django.urls import reverse_lazy, reverse

from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.template.loader import get_template
from django.conf import settings

from django.contrib.auth.decorators import login_required

# Create your views here.

class ManagerHomeView(LoginRequiredMixin, ListView):
    model = Manager
    template_name = 'manager/home.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_manager:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tags = Tag.objects.all().order_by('-id')[:3]        
        product = Product.objects.all().order_by('-id')[:3]
        home_slider = HomeTopSlider.objects.all().order_by('-id')[:3]  
        our_products_are = OurProductsAre.objects.all()    
        category = Category.objects.all().order_by('-id')[:3]     
        delivery_team = DeliveryTeamProfile.objects.all().order_by('-id')     
        supplier_profile = SupplierProfile.objects.all().order_by('-id')[:3]
        supplier_waiting_list = SupplierForm.objects.all().order_by('-id')[:3]
        blog = BlogModel.objects.all().order_by('-id')[:5]
     
        context['tags'] = tags
        context['product'] = product
        context['home_slider'] = home_slider
        context['category'] = category
        context['our_products_are'] = our_products_are
        context['delivery_team'] = delivery_team
        context['supplier_profile'] = supplier_profile
        context['supplier_waiting_list'] = supplier_waiting_list
        context['blog'] = blog

        return context


#Home Main Sliders##
#List Sliders and create more sliders
class HomeSliderListView(LoginRequiredMixin, CreateView):
    model = HomeTopSlider
    fields = ['title', 'image', 'detail']
    template_name = 'manager/home_sliders.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_manager:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sliders = HomeTopSlider.objects.all()
        context['sliders'] = sliders
        return context 
    
    #Redirect to same page
    def get_success_url(self):
        return reverse('manager:home_sliders')    


#Our Products Are
#List and create 
class OurProductsAreView(LoginRequiredMixin, CreateView):
    model = OurProductsAre
    fields = ['image', 'info']
    template_name = 'manager/our_products_are.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_manager:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        info = OurProductsAre.objects.all()
        context['info'] = info
        return context 
    
    #Redirect to same page
    def get_success_url(self):
        return reverse('manager:our_products_are')  


##Tags View##
#Shows List of tags and allows to add tags 
class TagListView(LoginRequiredMixin, CreateView):
    model = Tag
    fields = ['title']
    template_name = 'manager/tags_list.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_manager:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()

        tags = Tag.objects.all().order_by('-id')
        context['tags'] = tags
        return context   

    #Redirect to same page
    def get_success_url(self):
        return reverse('manager:tag_list')


class DeleteTagView(LoginRequiredMixin, DeleteView):
    model = Tag
    template_name = 'manager/delete_tag.html'
    success_url = reverse_lazy('manager:tag_list')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_manager:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('login')


############

##Product View##

#Shows List of products and allows to add product 
class ProductListView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductCreateForm
    template_name = 'manager/product_list.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_manager:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()
        context['products'] = products

        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        return context

    def get_success_url(self): 
        return reverse('manager:product_list')   


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductCreateForm
    template_name = 'manager/product_update.html'
    context_object_name = 'product'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_manager:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('login')    

    def get_success_url(self):
        return reverse('manager:product_list') 


class DeleteProductView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = 'manager/delete_product.html'
    success_url = reverse_lazy('manager:product_list')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_manager:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('login')

##########################################
   
##Category View##

#Shows List of categories and allows to add category 
class CategoryListView(LoginRequiredMixin, CreateView):
    model = Category
    fields = ['parent', 'title']
    template_name = 'manager/category_list.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_manager:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('login')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.all()
        context['category'] = category

        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        return context 

    def get_success_url(self):
        return reverse('manager:category_list')    


class DeleteCategoryView(LoginRequiredMixin, DeleteView):
    model = Category
    template_name = 'manager/delete_category.html'
    success_url = reverse_lazy('manager:category_list')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_manager:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('login')


##########################################
      
##Delivery Team View##

#Shows List of Delivery Team and allows to add Delivery Team 
##Refactor this code to CBV. See earlier commits to check error in CBV process.
@login_required
def delivery_team_list(request):
    if request.user.is_authenticated and request.user.is_manager:
        if request.method == "POST":
            form = DeliveryTeamRegisterForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                email = form.cleaned_data['email']
                password = form.cleaned_data['password1']

                form.save()

                context = {
                    'username': username,
                    'email': email,
                    'password': password,
                    # 'site_url': settings.base.py.SITE_URL
                }
                send_mail(           
                    subject = 'Account Created',
                    message = get_template('registration/email/registration_email.txt').render(context),
                    from_email = 'gaurab@email.com',
                    recipient_list = [email],
                ) 
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))         
        
        qs = DeliveryTeamProfile.objects.all().order_by('-id') 
        form = DeliveryTeamRegisterForm()
        context = {
            'deliveryteamprofile': qs,
            'form': form,  
        } 
        return render(request, 'manager/delivery_team_list.html', context)  
    else:
        return redirect('login')         


class DeleteDeliveryTeamView(LoginRequiredMixin, DeleteView):
    model = DeliveryTeamProfile
    template_name = 'manager/delete_delivery_team.html'
    success_url = reverse_lazy('manager:delivery_team_list')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_manager:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('login')

templates/manager/blog_create.html
{% extends 'other_base.html' %}
 
{% block title %}<title>Blog List</title>{% endblock %}

{% load crispy_forms_tags%}

{% block main %}
    <div class="container-fluid mt-5">
      <div class="row wow fadeIn align-items-center">
        <div class="col-md-10 mb-5">
            <div class="card card-list">
                <div class="card-header white d-flex justify-content-between align-items-center py-3">
                    <p class="h5-responsive font-weight-bold mb-0"><strong>Total:</strong> {{blog.count}}</p>
                </div>
                <div class="card-body">
                    <div class="text-center mb-5">
                        <strong>Blog List</strong>
                    </div>
                    <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">Blogs</th>
                        <th scope="col">Author</th>
                        <th scope="col">Created Time</th>
                        <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in blog %}
                            <tr>
                            <th scope="row"><a class="text-primary">{{item.post_title}}</a></th>
                            <th scope="row"><a class="text-primary">{{item.author}}</a></th>
                            <th scope="row"><a class="text-primary">{{item.posted_date}}</a></th>
                            <th>
                                <a class='btn btn-warning btn-sm mb-1' href="{% url 'manager:blog_update' item.id %}">Update</a>
                                <a class='btn btn-danger btn-sm' href="{% url 'manager:blog_delete' item.id %}">Delete</a>
                            </th>
                            </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                </div>
            </div> 
        </div>
        <div class="col-md-10">
            <div class='card'>
                <div class='text-center mt-3'>
                    <strong>Create Blog</strong>  
                </div>
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form|crispy}}
                        <button class='btn btn-dark' type="submit">Create</button>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </div>          

{% endblock %}

templates/manager/campaign.html
{% extends 'other_base.html' %}
 
{% block title %}<title>Campaign List</title>{% endblock %}


{% block main %}
<div class="container-fluid mt-5">
    <div class="row wow fadeIn align-items-center">
      <div class="col-md-10 mb-5">
          <div class="card card-list">
              <div class="card-header white d-flex justify-content-between align-items-center py-3">
                  <p class="h5-responsive font-weight-bold mb-0"><strong>Total:</strong> {{campaigns.count}}</p>
              </div>
              <div class="card-body">
                  <div class="text-center mb-5">
                      <strong>Campaigns List</strong>
                  </div>
                  <table class="table">
                  <thead>
                      <tr>
                      <th scope="col">Title</th>
                      <th scope="col">Product</th>
                      <!-- <th scope="col">Created Time</th> -->
                      <th scope="col">Action</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for item in campaigns %}
                          <tr>
                          <th scope="row"><a class="text-primary">{{item.title}}</a></th>
                          <th scope="row"><a class="text-primary">{{item.product.title}}</a></th>
                          <!-- <th scope="row"><a class="text-primary">{{item.posted_date}}</a></th> -->
                          <th>
                              <a class='btn btn-warning btn-sm mb-1' href="{% url 'manager:campaign_update' item.pk %}">Update</a>
                              <a class='btn btn-danger btn-sm' href="{% url 'manager:campaign_delete' item.pk %}">Delete</a>
                          </th>
                          </tr>
                      {% endfor %}
                  </tbody>
                  </table>
              </div>
          </div> 
      </div>

      {% include 'utils/create_item.html' with title='Create New Campaign' %}

    </div>
</div> 
{% endblock main %}
    

templates/manager/delete_supplier.html
{% extends 'other_base.html' %}
 
{% block title %}<title>Delete Delivery Team</title>{% endblock %}

{% block main %}

<div class="container" style="margin-top: 200px; margin-bottom: 232px;">
    <div class="card">
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <h4>Are You Sure You Want To Delete This Supplier <strong>{{deliveryteamprofile.username}}</strong>?</h4>
                <br>
                <a href="{% url 'manager:supplier_list' %}" class="btn btn-success btn-sm">Cancel</a>
                <button type="submit" class='btn btn-danger btn-sm'>Delete</button>  
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/manager/delivery_team_list.html
{% extends 'other_base.html' %}
 
{% block title %}<title>Delivery Team List</title>{% endblock %}

{% load crispy_forms_tags%}

{% block main %}
    <div class="container-fluid mt-5">
        <div class="row wow fadeIn">
            <div class="col-md-10 mb-5">
                <div class="card card-list">
                    <div class="card-header white d-flex justify-content-between align-items-center py-3">
                        <p class="h5-responsive font-weight-bold mb-0"><strong>Total:</strong> {{deliveryteamprofile.count}}</p>
                    </div>
                    <div class="card-body">
                        <div class="text-center mb-5">
                            <strong>Delivery Team List</strong>
                        </div>
                        <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">Teams</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for team in deliveryteamprofile %}
                                <tr>
                                <th scope="row"><a class="text-primary">{{team.username}}</a></th>
                                <th></th>
                                <th></th>
                                <th><a class='btn btn-danger btn-sm' href="{% url 'manager:delete_delivery_team' team.id %}">Delete</a></th>
                                </tr>
                            {% endfor %}
                        </tbody>
                        </table>
                    </div>
                </div> 
            </div>
            <div class="col-md-10">
                <div class='card'>
                    <div class='text-center mt-3'>
                        <strong>Create Delivery Team</strong>  
                    </div>
                    <div class="card-body">
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form|crispy}}
                            <button class='btn btn-dark' type="submit">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/manager/supplier_form.html
{% extends 'other_base.html' %}
 
{% block title %}<title>Supplier Status List</title>{% endblock %}

{% block main %}
    <div class="container-fluid mt-5">
        <div class="row wow fadeIn">
            <div class="col-md-10 mb-5">
                <div class="card card-list">
                    <div class="card-header white d-flex justify-content-between align-items-center py-3">
                        <p class="h5-responsive font-weight-bold mb-0"><strong>Total:</strong> {{status_waiting.count}}</p>
                    </div>
                    <div class="card-body">
                        <div class="text-center mb-5">
                            <strong>Supplier Waiting List</strong>
                        </div>
                        <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">Supplier Name</th>
                            <th scope="col">Shop Name</th>
                            <th scope="col">Phone Number</th>
                            <th scope="col">Status</th>
                            <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for supplier in status_waiting %}
                                <tr>
                                <th scope="row"><a class="text-primary">{{supplier.supplier_name}}</a></th>
                                <th scope="row"><a class="text-primary">{{supplier.shop_name}}</a></th>
                                <th scope="row"><a class="text-primary">{{supplier.supplier_phone_num}}</a></th>
                                <th scope="row"><a class="text-primary">{{supplier.status}}</a></th>
                                <th><a class='btn btn-warning btn-sm' href="{% url 'manager:supplier_waiting_update' supplier.id %}">Action</a></th>
                                </tr>
                            {% endfor %}
                        </tbody>
                        </table>
                    </div>
                </div> 
            </div>
            <div class="col-md-10 mb-5">
                <div class="card card-list">
                    <div class="card-header white d-flex justify-content-between align-items-center py-3">
                        <p class="h5-responsive font-weight-bold mb-0"><strong>Total:</strong> {{status_accepted.count}}</p>
                    </div>
                    <div class="card-body">
                        <div class="text-center mb-5">
                            <strong>Supplier Accepted List</strong>
                        </div>
                        <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">Supplier Name</th>
                            <th scope="col">Shop Name</th>
                            <th scope="col">Phone Number</th>
                            <th scope="col">Status</th>
                            <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for supplier in status_accepted %}
                                <tr>
                                <th scope="row"><a class="text-primary">{{supplier.supplier_name}}</a></th>
                                <th scope="row"><a class="text-primary">{{supplier.shop_name}}</a></th>
                                <th scope="row"><a class="text-primary">{{supplier.supplier_phone_num}}</a></th>
                                <th scope="row"><a class="text-primary">{{supplier.status}}</a></th>
                                <th><a class='btn btn-warning btn-sm' href="{% url 'manager:supplier_waiting_update' supplier.id %}">Action</a></th>
                                </tr>
                            {% endfor %}
                        </tbody>
                        </table>
                    </div>
                </div> 
            </div>
        </div>
        <div class="row wow fadeIn mt-5">
            <div class="col-md-10">
                <div class="card card-list">
                    <div class="card-header white d-flex justify-content-between align-items-center py-3">
                        <p class="h5-responsive font-weight-bold mb-0"><strong>Total:</strong> {{status_ignored.count}}</p>
                    </div>
                    <div class="card-body">
                        <div class="text-center mb-5">
                            <strong>Supplier Ignored List</strong>
                        </div>
                        <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">Supplier Name</th>
                            <th scope="col">Shop Name</th>
                            <th scope="col">Phone Number</th>
                            <th scope="col">Status</th>
                            <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for supplier in status_ignored %}
                                <tr>
                                <th scope="row"><a class="text-primary">{{supplier.supplier_name}}</a></th>
                                <th scope="row"><a class="text-primary">{{supplier.shop_name}}</a></th>
                                <th scope="row"><a class="text-primary">{{supplier.supplier_phone_num}}</a></th>
                                <th scope="row"><a class="text-primary">{{supplier.status}}</a></th>
                                <th><a class='btn btn-warning btn-sm' href="{% url 'manager:supplier_waiting_update' supplier.id %}">Action</a></th>
                                </tr>
                            {% endfor %}
                        </tbody>
                        </table>
                    </div>
                </div> 
            </div>
        </div>
    </div>

{% endblock %}

templates/manager/supplier_list.html
{% extends 'other_base.html' %}
 
{% block title %}<title>Supplier List</title>{% endblock %}

{% load crispy_forms_tags%}

{% block main %}
    <div class="container-fluid mt-5">
        <div class="row wow fadeIn">
            <div class="col-md-10 mb-5">
                <div class="card card-list">
                    <div class="card-header white d-flex justify-content-between align-items-center py-3">
                        <p class="h5-responsive font-weight-bold mb-0"><strong>Total:</strong> {{supplierprofile.count}}</p>
                    </div>
                    <div class="card-body">
                        <div class="text-center mb-5">
                            <strong>Supplier List</strong>
                        </div>
                        <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">Supplier</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for supplier in supplierprofile %}
                                <tr>
                                <th scope="row"><a class="text-primary">{{supplier.username}}</a></th>
                                <th></th>
                                <th></th>
                                <th>
                                    <a class='btn btn-warning btn-sm mb-1' href="{% url 'manager:supplier_update' supplier.pk %}">Update</a>
                                    <a class='btn btn-danger btn-sm' href="{% url 'manager:delete_supplier' supplier.id %}">Delete</a>
                                </th>
                                </tr>
                            {% endfor %}
                        </tbody>
                        </table>
                    </div>
                </div> 
            </div>
            <div class="col-md-10 mb-5">
                <div class='card'>
                    <div class='text-center mt-3'>
                        <strong>Create Supplier</strong>  
                    </div>
                    <div class="card-body">
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form|crispy}}
                            <button class='btn btn-dark' type="submit">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}