blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, create_comment


app_name='blog'

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('detail/<str:pk>', BlogDetailView.as_view(), name="detail"),
    path('comment', create_comment, name='comment'),
]

carts/urls.py
from django.urls import path
from .views import cart_home, update_cart


app_name = 'carts'

urlpatterns = [
    path('', cart_home, name='home'),
    path('update', update_cart, name='update'),
]

product/urls.py
from django.urls import path
from .views import (organicstoreListView, organic_station_detail, shop_page_view, CreateProductView,
    product_detail, ProductUpdateView, ProductDeleteView, SupplierProductsListView,
    create_comment, ProductSearchResultView, rate_product, CategoryProductView)


app_name = 'product'

urlpatterns = [
    path('organic-store', organicstoreListView.as_view(), name='organic_station'),
    path('organic-detail/<str:pk>', organic_station_detail, name='organic_detail'),
    path('shop', shop_page_view, name='shop_page'),
    path('create', CreateProductView.as_view(), name='create'),
    path('detail/<str:pk>', product_detail, name='detail'),
    path('update/<str:pk>', ProductUpdateView.as_view(), name='update'),
    path('delete/<str:pk>', ProductDeleteView.as_view(), name='delete'),
    path('all-products/<str:email>', SupplierProductsListView.as_view(), name='all_products'),
    path('comment', create_comment, name='comment'),
    path('search/', ProductSearchResultView.as_view(), name='search'),
    path('rate-product', rate_product, name='rate-product'),
    path('catproduct/<str:pk>', CategoryProductView.as_view(), name='cat-product'),
]

product/forms.py
from django import forms
from .models import Product, Tag


class ProductCreateForm(forms.ModelForm):
    more_images = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={
        "class": "form-control",
        "multiple": True
    }))

    tags = forms.ModelMultipleChoiceField(queryset= Tag.objects.all(), required=False)

    class Meta:
        model = Product
        fields = ['category', 'title', 'price', 'description', 'image', 'video', 'discount_price',
                    'season_choice', 'is_organic_station', 'tags']

        widgets = {
            "title": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product title here..."
            }),
            "price": forms.NumberInput(attrs={
                "class": "form-control",
                "placeholder": "Price of the product..."
            }),
            "description": forms.Textarea(attrs={
                "class": "form-control",
                "placeholder": "Description of the product...",
                "rows": 5,
                'style': 'resize:none'
            }),
            "image": forms.ClearableFileInput(attrs={
                "class": "form-control"
            }),
            "video": forms.TextInput(attrs={
                "class": "form-control"
            }),
            "discount_price": forms.NumberInput(attrs={
                "class": "form-control",
                "placeholder": "Discount price of the product..."
            }),
            "season_choice": forms.Select(attrs={
                "class": "form-control"
            }),
        }


    

product/views.py
from django.shortcuts import render, redirect, get_object_or_404

from manager.models import HomeTopSlider, OurProductsAre
from .models import (Product, Tag, ProductImage, Comment, Rating, Category, Campaign)
from .forms import ProductCreateForm
from carts.models import Cart, CartItem
from blog.models import BlogModel
from django.contrib.auth import get_user_model

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView 

from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy

from django.contrib import messages

from product.templatetags import custom_tags

from django.db.models import Q

from django.utils.timezone import now
from datetime import timedelta

# Create your views here.

USER = get_user_model()

#Home Page View
def home_view(request):

    #Home Slider
    slider = HomeTopSlider.objects.all()
    #nyano organic
    organic = Product.objects.filter(is_organic_station=True)[:10]
    #Categories
    category = Category.objects.all()[:3]
    #Our Products Are
    # our_products_are = OurProductsAre.objects.all()
    #Deal of the Week
    deal_of_the_week = Campaign.objects.filter(title='Deal of the Week')
    #Latest Products
    latest_product = Product.objects.all().order_by('-id')[:10]
    #Blogs
    blog = BlogModel.objects.all().order_by('-id')[:3]

    ##Find best place to keep cart deletion code    
    #Auto delete cart after creation of 1 day
    Cart.objects.filter(date_created__lte=now()-timedelta(days=1)).delete()

    #Colors on tags
    color = ['primary', 'secondary', 'success', 'danger', 'warning', 'info']

    context = {
        'slider': slider,
        'organic': organic,
        'product': latest_product,
        'category': category,
        'deal_of_the_week': deal_of_the_week,
        'color': color,
        'blog': blog,
    }
    return render(request, 'home.html', context)


class organicstoreListView(ListView):
    model = Product
    template_name = 'product/organic_station.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs = Product.objects.filter(is_organic_station=True)
        context['organic_station'] = qs
        return context


def organic_station_detail(request, pk):
    product = Product.objects.get(id=pk, is_organic_station=True)
    
    ##Rafactor Rating Code if possible
    #Product Rating On Product Detail
    rating_qs = Rating.objects.filter(product=product)
    if rating_qs:
        for x in rating_qs:
            not_rated = False
            rating = x.rating
    else:
        not_rated = True
        rating = 0

    #For Adding product to Cart
    cart_obj, new_obj = Cart.objects.new_or_get(request)

    #For Comments and replies display
    comments = Comment.objects.filter(product=product, parent=None)
    replies = Comment.objects.filter(product=product).exclude(parent=None)
    replyDict = {}
    for reply in replies:
        if reply.parent.id not in replyDict.keys():
            replyDict[reply.parent.id] = [reply]
        else:
            replyDict[reply.parent.id].append(reply)

    ####Refactor this query if possible####
    #For recommending similar products on the basis of tags
    tags_of_product = product.tags.all()
    similar_products_query = []
    similar_products = None

    #List of queries of products
    for tag in tags_of_product:
        qs = Product.objects.filter(tags__title__contains=tag.title).exclude(id=product.id)
        if qs:
            similar_products_query.append(qs)
    #Query of products
    if similar_products_query:        
        for item in similar_products_query:
            similar_products = item
    
    product_and_rating={}
    #Ratings of similar products
    if similar_products is not None:
        for x in similar_products:
            rating_qs = Rating.objects.filter(product=x)
            if rating_qs:
                for rx in rating_qs:
                    product_and_rating[x] = rx.rating
            else:
                product_and_rating[x] = 0 
            
    #########################################     
    #For colors in tags
    color = ['primary', 'secondary', 'success', 'danger', 'warning', 'info']

    context = {
        'product': product,
        'cart': cart_obj,
        'color': color,
        'rating': range(rating),
        'no_rating': range(5-rating),
        'not_rated': not_rated,
        'comments': comments,
        'reply': replyDict,
        'similar_items': similar_products,
        'product_rating': product_and_rating.items(),
    }
    return render(request, 'product/organic_station_detail.html', context)

#Shop Page View
def shop_page_view(request):
    product = Product.objects.all()

    #Categories
    category = Category.objects.all()

    ##Find best place to keep cart deletion code    
    #Auto delete cart after creation of 1 minute
    Cart.objects.filter(date_created__lte=now()-timedelta(days=1)).delete()
    
    ##Color on tags
    color = ['primary', 'secondary', 'success', 'danger', 'warning', 'info']

    context = {
        'product': product,
        'category': category,
        'color': color,
    }
    return render(request, 'product/shop_page.html', context)


#Product CRUD Section Starts
class CreateProductView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductCreateForm
    template_name = 'product/product_create.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.supplier = self.request.user
        p = form.save()
        images = self.request.FILES.getlist('more_images')
        for i in images:
            ProductImage.objects.create(product=p, image=i)        
        return super().form_valid(form) 

def product_detail(request, pk):
    product = Product.objects.get(id=pk)
    
    ##Rafactor Rating Code if possible
    #Product Rating On Product Detail
    rating_qs = Rating.objects.filter(product=product)
    if rating_qs:
        for x in rating_qs:
            not_rated = False
            rating = x.rating
    else:
        not_rated = True
        rating = 0

    #For Adding product to Cart
    cart_obj, new_obj = Cart.objects.new_or_get(request)

    #For Comments and replies display
    comments = Comment.objects.filter(product=product, parent=None)
    replies = Comment.objects.filter(product=product).exclude(parent=None)
    replyDict = {}
    for reply in replies:
        if reply.parent.id not in replyDict.keys():
            replyDict[reply.parent.id] = [reply]
        else:
            replyDict[reply.parent.id].append(reply)

####Refactor this query if possible####
    #For recommending similar products on the basis of tags
    tags_of_product = product.tags.all()
    similar_products_query = []
    similar_products = None

    #List of queries of products
    for tag in tags_of_product:
        qs = Product.objects.filter(tags__title__contains=tag.title).exclude(id=product.id)
        if qs:
            similar_products_query.append(qs)
    #Query of products
    if similar_products_query:        
        for item in similar_products_query:
            similar_products = item
    
    product_and_rating={}
    #Ratings of similar products
    if similar_products is not None:
        for x in similar_products:
            rating_qs = Rating.objects.filter(product=x)
            if rating_qs:
                for rx in rating_qs:
                    product_and_rating[x] = rx.rating
            else:
                product_and_rating[x] = 0 
            
#########################################     
    #For colors in tags
    color = ['primary', 'secondary', 'success', 'danger', 'warning', 'info']

    context = {
        'product': product,
        'cart': cart_obj,
        'color': color,
        'rating': range(rating),
        'no_rating': range(5-rating),
        'not_rated': not_rated,
        'comments': comments,
        'reply': replyDict,
        'similar_items': similar_products,
        'product_rating': product_and_rating.items(),
    }
    return render(request, 'product/product_detail.html', context)

class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductCreateForm
    template_name = 'product/product_update.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.supplier = self.request.user       
        
        product = self.get_object() 
        
        # Clear existing images
        for post_image in ProductImage.objects.filter(product=product):
            post_image.delete()
        
        # Updating new images
        images = self.request.FILES.getlist('more_images')        
        for i in images:
            ProductImage.objects.create(product=product, image=i)

        form.save()
        return super().form_valid(form)

    # If user is supplier update the product
    def test_func(self):
        product = self.get_object()
        if self.request.user == product.supplier:
            return True
        return False    

class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('home')
    template_name = 'product/product_delete.html'

    # If user is supplier delete the product
    def test_func(self):
        product = self.get_object()
        if self.request.user == product.supplier:
            return True
        return False    
#Product CRUD Section Ends


#Category Wise Product Start
class CategoryProductView(ListView):
    model = Category
    template_name = 'product/category_wise_product.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.kwargs['pk']
        qs = Product.objects.filter(category=category)   

templates/product/all_products_of_supplier.html
{% extends 'base.html' %} 


{% block title %}<title>All Products</title>{% endblock %}

{% block main %}
<div class="my-5"></div> <hr>
<div class="container py-5 mt-5">
  <header class="text-center">
    <h1 class="display-4">Your Products</h1>
    <p class="font-italic mb-0">Have a quick look at your store.</p>
  </header>

  <div class="row">
    <div class="col-lg-11 mx-auto">
      {% if product %}
      <div class="row py-5">
        {% for item in product %}  
          <div class="col-lg-4">
            <a href="{% url 'product:detail' item.id %}" >
            <figure class="caption-3 mb-0 shadow-sm p-3 bg-white">
              <img src="{{item.image.url}}" alt="" class="w-100">
              <figcaption class="px-5 py-3 bg-white shadow-sm">
                
                  <h2 class="h5 mb-1 font-weight-bold">{{item.title}}</h2>
                
                <p class="mb-0 text-small font-italic text-muted">Rs {{item.price}}</p>
              </figcaption>
            </figure>
            </a>
          </div>
        {% endfor %}

      </div>
      {% else %}
      <div>
        <h5>No products to show. Please add products to view them here.</h5>
      </div>
      {% endif %}
    </div>
  </div>

{% endblock %}

templates/product/category_wise_product.html
{% extends 'base.html' %}

{% load static %}
{% load custom_tags %}

<!-- {% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/plugins/jquery-ui-1.12.1.custom/jquery-ui.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/categories_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/categories_responsive.css' %}">
{% endblock %} -->



{% block title %}<title>{{product.first.category}}</title>{% endblock %}

{% block main %}

  <div class="super_container">
    <div class="container product_section_container">
      <div class="row">
        <div class="col product_section clearfix">
          <div class="breadcrumbs d-flex flex-row align-items-center" style="margin-top: -30px;">
            <ul>
              <li><a href="{% url 'home' %}">Home</a></li>
              <li class="active"><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>{{product.first.category}}</a></li>
            </ul>
          </div>
          <div class="main_content">
            <div class="products_iso">
              <div class="row">
                    {% for item in product %}
                    <div class="col-md-3 product-item mb-5">
                      <a href="{% url 'product:detail' item.id %}">
                        <div class="product discount product_filter">
                          <div class="product_image">
                            <img src="{{item.imageURL}}" alt="">
                          </div>
                          <div class="favorite favorite_left"></div>
                          <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>{{item.category}}</span></div>
                          <div class="product_info">
                            <h6 class="product_name">{{item.title}}</h6>
                            <div class="product_price">Rs{{item.price_after_discount}}<span>Rs{{item.price}}</span></div>
                          </div>
                        </div>
                      </a>
                      <div class="add_to_cart_button mb-5">
                        <form method='POST' action="{% url 'carts:update' %}">
                          {% csrf_token %}
                          <input type="hidden" value="{{ item.id }}" name='products_id'>
                          <input type='hidden' name='qty' value='1'/>
                          <button class="btn btn-danger" type="submit" name='add' style="width: 100%;">
                            Add to cart
                            <span><i class="fa fa-cart-plus"></i></span>
                          </button>   
                        </form>
                      </div>
                    </div>
                    {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}


{% block js %}
<!-- <script src="{% static 'coloshop/plugins/jquery-ui-1.12.1.custom/jquery-ui.js' %}"></script> -->
<!-- <script src="{% static 'coloshop/js/categories_custom.js' %}"></script> -->
{% endblock %}

templates/product/organic_station.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/plugins/jquery-ui-1.12.1.custom/jquery-ui.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/categories_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/categories_responsive.css' %}">
{% endblock %}

<!-- {% block js %}
<script src="{% static 'coloshop/plugins/jquery-ui-1.12.1.custom/jquery-ui.js' %}"></script>
<script src="{% static 'coloshop/js/categories_custom.js' %}"></script>
{% endblock %} -->

{% block title %}
<title>Organic Shop</title>
{% endblock %}

{% block main %}

<div class="super_container">
	<div class="container product_section_container">
		<div class="row">
			<div class="col product_section clearfix">

				<div class="breadcrumbs d-flex flex-row align-items-center">
					<ul>
						<li><a href="{% url 'home' %}">Home</a></li>
						<li class="active"><a><i class="fa fa-angle-right" aria-hidden="true"></i>Organic Station</a></li>
					</ul>
				</div>

				<!-- Main Content -->
				<div class="main_content">
					<div class="products_iso">
						<div class="row">
							{% for item in organic_station %}
							<div class="product-item col-md-3" style="margin-top: 20px;">
								<div class="product discount product_filter">
									<a href="{% url 'product:organic_detail' item.id %}">
										<div class="product_image">
											<img src="{{item.imageURL}}" alt="" style="display: block;">
										</div>
									</a>
									<div class="favorite favorite_left"></div>
									<div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>New</span></div>
									<div class="product_info">
										<h6 class="product_name"><a href="{% url 'product:organic_detail' item.id %}">{{item.title}}</a></h6>
										<div class="product_price">Rs{{item.price_after_discount}}<span>Rs{{item.price}}</span></div>
									</div>
								</div>
								<div class="red_button add_to_cart_button">
									<form method='POST' action="{% url 'carts:update' %}">
										{% csrf_token %}
										<input type="hidden" value="{{item.id}}" name='products_id'>
					
										<input type='hidden' name='qty' value='1'/>
					
										<button class="btn btn-danger btn-md" type="submit" name='add'>Add to cart <i class="fa fa-cart-plus"></i></button>    
									</form> 
								</div>  
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/product/organic_store.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/plugins/jquery-ui-1.12.1.custom/jquery-ui.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/categories_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/categories_responsive.css' %}">
{% endblock %}

{% block js %}
<script src="{% static 'coloshop/plugins/jquery-ui-1.12.1.custom/jquery-ui.js' %}"></script>
<script src="{% static 'coloshop/js/categories_custom.js' %}"></script>
{% endblock %}

{% block title %}
<title>Organic Shop</title>
{% endblock %}

{% block main %}

<div class="super_container">
	<div class="container product_section_container">
		<div class="row">
			<div class="col product_section clearfix">

				<div class="breadcrumbs d-flex flex-row align-items-center">
					<ul>
						<li><a href="{% url 'home' %}">Home</a></li>
						<li class="active"><a><i class="fa fa-angle-right" aria-hidden="true"></i>Organic Store</a></li>
					</ul>
				</div>

				<!-- Main Content -->
				<div class="main_content">
					<div class="products_iso">
						<div class="row">
							<div class="col">
								<div class="product-grid">
									{% for item in organic_store %}
									<div class="product-item" style="margin-top: 20px;">
										<div class="product discount product_filter">
											<a href="{% url 'product:organic_detail' item.id %}">
												<div class="product_image">
													<img src="{{item.imageURL}}" alt="" style="display: block;">
												</div>
											</a>
											<div class="favorite favorite_left"></div>
											<div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>-$20</span></div>
											<div class="product_info">
												<h6 class="product_name"><a href="{% url 'product:organic_detail' item.id %}">{{item.title}}</a></h6>
												<div class="product_price">Rs{{item.price_after_discount}}<span>Rs{{item.price}}</span></div>
											</div>
										</div>
										<div class="red_button add_to_cart_button">
											<form method='POST' action="{% url 'carts:update' %}">
												{% csrf_token %}
												<input type="hidden" value="{{item.id}}" name='products_id'>
							
												<input type='hidden' name='qty' value='1'/>
							
												<button class="btn btn-danger btn-md" type="submit" name='add'>Add to cart </button>    
											</form> 
										</div>  
									</div>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/product/product_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags%}

{% block main %}
<div class="container mt-5">
    <div class="row mt-5">
        <div class="col clearfix mt-5">
            <div class="container mt-5">
                <header class="text-center mt-5">
                    <span class="display-4"> Add a New Product</span>
                </header><hr>
                <div class="row align-items-center">
                    <form action="{% url 'product:create' %}" method="post" enctype="multipart/form-data" class="col-md-10 ml-5 mt-5">
                        {% csrf_token %}
                
                        {{form|crispy}}
                
                        <button type="submit" class="btn btn-warning">ADD</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

templates/product/product_delete.html
{% extends 'base.html' %}

{% block title %}<title>Delete Product</title>{% endblock %}

{% block main %}

<div class="container" style="margin-top: 200px;">
    <form action="" method="post">
        {% csrf_token %}

        <h4>Are You Sure You Want To Delete This Product <strong>{{product}}</strong>?</h4>
        
        <br>
        <a href="{% url 'product:detail' product.id %}" class="btn btn-success btn-lg">Cancel</a>
        <button type="submit" class='btn btn-danger btn-lg'>Delete</button>  
    </form>
</div>

{% endblock %}

templates/product/product_update.html
{% extends 'base.html' %}

{% block title %}<title>Update Product</title>{% endblock %}

{% block main %}

<div class="container mt-5">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{form.as_p}}

        <a href="{% url 'product:detail' product.id %}" class='btn btn-danger btn-lg'>Cancel</a>
        <button type="submit" class='btn btn-success btn-lg'>Update</button>
    </form>
</div>

{% endblock %}

templates/product/shop_page.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/plugins/jquery-ui-1.12.1.custom/jquery-ui.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/categories_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/categories_responsive.css' %}">
{% endblock %}



{% block title %}
<title>Shop</title>
{% endblock %}

{% block main %}

<div class="super_container">
	<div class="container product_section_container">
		<div class="row">
			<div class="breadcrumbs d-flex flex-row align-items-center">
				<ul>
					<li><a href="{% url 'home' %}">Home</a></li>
					<li class="active"><a><i class="fa fa-angle-right" aria-hidden="true"></i>Shop</a></li>
				</ul>
			</div>
			<div class="col-md-2 product_section clearfix">

				<!-- Sidebar -->

				<div class="sidebar">
					<div class="sidebar_section">
						<div class="sidebar_title">
							<h5>Product Category</h5>
						</div>
						<ul class="sidebar_categories">
                            {% for item in category %}
							<li><a href="{% url 'product:cat-product' item.pk %}">{{item.title}}</a></li>
                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>

			<div class="col-md-10">

				<!-- Main Content -->
				<div class="main_content">
					<div class="products_iso">
						<div class="row">
							{% for item in product %}
							<div class="product-item mr-5" style="margin-top: 20px;">
								<div class="product discount product_filter">
									<a href="{% url 'product:detail' item.id %}">
										<div class="product_image">
											
											{% if item.imageURL %}
											<img src="{{item.imageURL}}" alt="">
											{% else %}
											<img class="img-responsive" src="https://images.unsplash.com/photo-1589606743932-747c74e7330e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80" alt="">
											{% endif %}
												
										</div>
									</a>
									<div class="favorite favorite_left"></div>
									<div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>New</span></div>
									<div class="product_info">
										<h6 class="product_name"><a href="{% url 'product:detail' item.id %}">{{item.title}}</a></h6>
										<div class="product_price">Rs {{item.price_after_discount}}<span>Rs {{item.price}}</span></div>
									</div>
								</div>
								<div class="red_button add_to_cart_button">
									<form method='POST' action="{% url 'carts:update' %}">
										{% csrf_token %}
										<input type="hidden" value="{{item.id}}" name='products_id'>
					
										<input type='hidden' name='qty' value='1'/>
					
										<button class="btn btn-danger btn-md" type="submit" name='add'>Add to cart <i class="fa fa-cart-plus ml-2"></i></button>    
									</form> 
								</div>  
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}


<!-- {% block js %}
<script src="{% static 'coloshop/plugins/jquery-ui-1.12.1.custom/jquery-ui.js' %}"></script>
<script src="{% static 'coloshop/js/categories_custom.js' %}"></script>
{% endblock %} -->