blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, create_comment


app_name='blog'

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('detail/<str:pk>', BlogDetailView.as_view(), name="detail"),
    path('comment', create_comment, name='comment'),
]

carts/urls.py
from django.urls import path
from .views import cart_home, update_cart


app_name = 'carts'

urlpatterns = [
    path('', cart_home, name='home'),
    path('update', update_cart, name='update'),
]

customer/urls.py
from django.urls import path
from .views import *

app_name = 'customer'

urlpatterns = [
    path('', CustomerProfileView.as_view(), name='home'),
    path('register-customer', RegisterCustomerView.as_view(), name='register'),
    path('edit-customer', customer_profile_edit, name='edit'), 
    path('confirm', registration_confirmation, name='confirm'),
    path('settings', CustomerSettingsView.as_view(), name='setting'),
    path('delete-account', customer_delete, name='delete_account'),
    path('subscribe_newsletter', subscribe_newsletter, name='subscribe_newsletter'),
    path('contact_us', TemplateView.as_view(template_name='contact_us.html'), name='contact_us'),
    path('contact_us_ajax', contact_us_view, name='contact_us_ajax'),
]

product/urls.py
from django.urls import path
from .views import (organicstoreListView, organic_station_detail, shop_page_view, CreateProductView,
    product_detail, ProductUpdateView, ProductDeleteView, SupplierProductsListView,
    create_comment, ProductSearchResultView, rate_product, CategoryProductView)


app_name = 'product'

urlpatterns = [
    path('organic-store', organicstoreListView.as_view(), name='organic_station'),
    path('organic-detail/<str:pk>', organic_station_detail, name='organic_detail'),
    path('shop', shop_page_view, name='shop_page'),
    path('create', CreateProductView.as_view(), name='create'),
    path('detail/<str:pk>', product_detail, name='detail'),
    path('update/<str:pk>', ProductUpdateView.as_view(), name='update'),
    path('delete/<str:pk>', ProductDeleteView.as_view(), name='delete'),
    path('all-products/<str:email>', SupplierProductsListView.as_view(), name='all_products'),
    path('comment', create_comment, name='comment'),
    path('search/', ProductSearchResultView.as_view(), name='search'),
    path('rate-product', rate_product, name='rate-product'),
    path('catproduct/<str:pk>', CategoryProductView.as_view(), name='cat-product'),
]

templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title>About Us</title>{% endblock %}

    
    
  {% block main %}
      <div class="page-header p-3 px-5 pt-5">
      </div>
      <div class="container-fluid">
        <div class="row px-3 wow zoomIn">
        <div class="col-md-5 ml-auto">
            <h1><p class="display-4 text-dark">Organic & <br> Farm Fresh </p></h1><hr>
            <p class="p1 px-3">KAii Mart aims to provide organic fruits and vegetables, as well as ecological, ethical and fair products to the consumers at an affordable price. We do fast deliver all over Nepal.</p>
          </div>
          <div class="col-md-7  ml-auto pl-5">
            <img src="{% static 'img/55.jpg' %}" alt="" class="img-fluid">
          </div>
        </div>
      </div>
      <div class="container-fluid" data-aos="fade-up"  data-aos-duration="5000">
        <div class="row px-3 pt-5" data-aos="fade-up">
            <div class="col-md-7 pt-5 ml-auto" data-aos="fade-up">
              <img src="{% static 'img/1.jpg' %}" alt="" class="img-fluid" >
            </div>
            <div class="col-md-5 pt-5 ml-auto">
              <h1><p class="display-4 text-dark">Eat Healthy</p></h1><hr>
              <p class="p1 px-3" >KAii Mart aims to provide organic fruits and vegetables, as well as ecological, ethical and fair products to the consumers at an affordable price. We do fast deliver all over Nepal.</p>
            </div>
        </div>
      </div>
  {% endblock %}
      

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/bootstrap4/bootstrap.min.css' %}">
    <link href="{% static 'coloshop/plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/plugins/OwlCarousel2-2.2.1/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/main_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/responsive.css' %} ">
    <!-- <link href="css/about.css" rel="stylesheet"> -->
    <link href="{% static 'css/loader.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">

    <style>
      a:hover, button:hover{
        cursor: pointer;
      }
      .navbar_user li a{
        width: auto;
      }
    </style>

    <!-- Material Design Bootstrap -->
    <!-- <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">   -->
    
    {% block css %}
      
    {% endblock %}

    {% block title %}

    {% endblock %}

  </head>

  <body onload="myFunction()" style="margin:0;" class="my-5">
    <div id="loader">
      <div class="loading">
        <span><img src="{% static 'img/logo.png' %}" height="88px" width="50px" align="center"></span>
      </div>
    </div>
    {% include 'utils/navbar.html' %}
    
    <div style="display:none;" id="myDiv">
    {% block main %}
    {% endblock %}

    {% include 'footer.html' %}
    </div>

    <!-- Optional JavaScript -->
    <!-- SCRIPTS -->
    <script src="{% static 'coloshop/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'coloshop/styles/bootstrap4/popper.js' %}"></script>
    <script src="{% static 'coloshop/styles/bootstrap4/bootstrap.min.js' %}"></script>
    <script src="{% static 'coloshop/plugins/Isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'coloshop/plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

  
    <!-- MDB core JavaScript -->
    <!-- <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script> -->
  
     <!-- Initializations -->
     {% block js %}
     {% endblock %}
   

    <script>
      function  myFunction() {
        document.getElementById("loader").style.display = "none";
        document.getElementById("myDiv").style.display = "block";
      }
    </script>
    <script>
      var wow = new WOW(
        {
          boxClass:     'wow',      // animated element css class (default is wow)
          animateClass: 'animated', // animation css class (default is animated)
          offset:       0,          // distance to the element when triggering the animation (default is 0)
          mobile:       true,       // trigger animations on mobile devices (default is true)
          live:         true,       // act on asynchronously loaded content (default is true)
          callback:     function(box) {
            // the callback is fired every time an animation is started
            // the argument that is passed in is the DOM node being animated
          },
          scrollContainer: true,    // optional scroll container selector, otherwise use window,
          resetAnimation: true,     // reset animation on end (default is true)
        }
      );
      wow.init();
    </script>
    <script>
      {
        AOS.init();
      }
    </script>

    
    
  </body>
</html>

templates/contact_us.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
<title>Contact Us</title>
{% endblock title %}
    

{% block main %}
<div class="container contact-page mb-5">
    <div class="my-5 py-3"></div>
    <div class="text-center mb-5 wow bounceInUp">
        <span class="display-4">Get in touch with us! <i class="fa fa-phone-square ml-3" aria-hidden="true"></i></span>
    </div><hr>
    <div class="container-fluid">
        <div class="row px-5 align-items-center wow bounceInUp">
            <div class="col-sm-5">
            <div class="container-fluid">
            <img src="{% static 'img/9.jpg' %}" class="img-fluid" height="500" width="500">
            </div>
            </div>
            <div class="col-md-7 ml-auto">
                <h2><p class="text-success text-uppercase font-weight-bolder">For more enquiries</p> </h2>
                <form method="POST" id="enquiry-form">
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-row">
                        <div class="input-group col-lg-12 mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-user text-muted"></i>
                                </span>
                            </div>
                            <input type="text" class="form-control" id="fname" placeholder="First Name" name="name" required>
                        </div>
                        <div class="input-group col-lg-12 mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-user text-muted"></i>
                                </span>
                            </div>
                            <input type="text" class="form-control" id="lname" placeholder="Last Name" name="name" required>
                        </div>
                        <div class="input-group col-lg-12 mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-envelope text-muted"></i>
                                </span>
                            </div>
                            <input type="email" class="form-control" id="email" placeholder="Email" name="email" required>
                        </div>
                        <div class="input-group col-lg-12 mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-phone-square text-muted"></i>
                                </span>
                            </div>
                            <input type="tel" class="form-control" id="phoneNumber" placeholder="Phone Number" name="phone" required>
                        </div>
                        <div class="input-group col-lg-12 mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-lg border-right-0">
                                    <i class="fa fa-comment text-muted"></i>
                                </span>
                            </div>
                            <textarea class="form-control" aria-label="With textarea" id="message" placeholder="How can we help you?" name="text" rows="6" required></textarea>
                        </div> 
                    </div>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                </form>
            </div>
        </div>
    </div>
   
    <div class="container-fluid wow bounceInUp mt-5">
        <div class="text-center">
            <span class="display-4">Find us here!<i class="fa fa-map-marker ml-3" aria-hidden="true"></i></span>
        </div><hr>
        <div class="row" data-aos="fade-up">
        <div class="mapouter pt-5">
        <div class="gmap_canvas">
            <iframe width="100%" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=sanepa%20chwok&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
            <a href="https://www.embedgooglemap.net">embed google map</a>
            <style>.mapouter{position:relative;text-align:right;height:500px;width:100%;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:100%;}</style>
            <a href="https://maps-google.github.io/embed-google-map/"></a>
        </div>
        </div> 
        </div>
    </div>

 </div> 
{% endblock main %}



{% block js %}
<script>
$(document).on('submit', '#enquiry-form', function(e){
      e.preventDefault(); // prevents the page from getting refreshed
      //now we write our ajax code
      $.ajax({
          type: 'POST',
          url: "{% url 'customer:contact_us_ajax' %}",
          data:{
                fname:$('#fname').val(),
                lname:$('#lname').val(),
                p_num:$('#phoneNumber').val(),
              email:$('#email').val(),
              message:$('#message').val(),
              csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
          },
          success:function(){
            //   document.getElementById("newsletter_email").value = '';
              swal("Got your Message! We'll contact with you soon!", {
                icon: 'success',
                buttons: false,
                timer: 2000,
              });
          },
          error: function() {
            // document.getElementById("newsletter_email").value = '';
            swal("Could not process the form. Please try again!", {
                icon: 'error',
                buttons: false,
                timer: 2000,
              });
          }
      });
      document.getElementById("enquiry-form").reset();
});
  </script> 
{% endblock js %}
    
    

   

templates/footer.html
{% load static %}


<footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center">
            <ul class="footer_nav">
              <li><a href="{% url 'blog:home' %}">Blog</a></li>
              <li><a href="{% url 'about' %}">About <span class="">KAii</span><span class="text-warning">Mart</span></a></li>
              <li><a href="{% url 'customer:contact_us' %}">Contact us</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center">
            <ul>
              <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="footer_nav_container">
            <div class="cr">© KAiiMart 2020-2021 All Rights Reserved.</div>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/newsletter.html
<section class="shop-newsletter section">
    <div class="container">
      <div class="inner-top">
        <div class="row">
          <div class="col-lg-8 offset-lg-2 col-12">
            <!-- Start Newsletter Inner -->
            <div class="inner">
              <h4>Newsletter</h4>
              <p> Subscribe to our newsletter and get <span>10%</span> off your first purchase</p>
              <form action="" method="get" target="_blank" class="newsletter-inner">
                <input name="EMAIL" placeholder="Your email address" required="" type="email">
                <button class="btn">Subscribe</button>
              </form>
            </div>
            <!-- End Newsletter Inner -->
          </div>
        </div>
      </div>
    </div>
  </section>

templates/other_base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/inhouse/main.css' %}">
    
    
    {% block css %}
      
    {% endblock %}

    {% block title %}

    {% endblock %}
  </head>

  <body>
    <div class="row">
      <div class="col-md-4">
      {% include 'inhouse/sidebar.html' %}
      </div>
      
      <div class="col-md-8 mb-5">

        {% block main %}
        {% endblock %}
      </div>
    </div>
    <!-- Optional JavaScript -->


    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript" src="{% static 'js/inhouse/main.js' %}"></script>

    {% block js %}
    {% endblock %}

    <script type="text/javascript">
      // Animations initialization
      new WOW().init();

    </script>
  </body>
</html>

templates/product_search_result.html
{% extends 'base.html' %}

{% load static %}
{% load custom_tags %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/plugins/jquery-ui-1.12.1.custom/jquery-ui.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/categories_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/categories_responsive.css' %}">
{% endblock %}

{% block js %}
<script src="{% static 'coloshop/plugins/jquery-ui-1.12.1.custom/jquery-ui.js' %}"></script>
<script src="{% static 'coloshop/js/categories_custom.js' %}"></script>
{% endblock %}

{% block title %}<title>Search Results..</title>{% endblock %}

{% block main %}

<div class='mt-5'></div>

<div class="super_container">
    <div class="container product_section_container">
        <span class="h5">  Search Results:- <strong class="shadow bg-success text-white px-3 py-1">{{object_list.count}}</strong> Product(s) Found </span> <hr>
        <div class="row">
            <div class="col product_section clearfix">
                <div class="main_content">
                    <div class="products_iso">
                    <div class="row">
                        {% if object_list %}
                            <!-- <div class="col"> -->
                            <!-- <div class="product-grid"> -->
                                {% for item in object_list %} 
                                    <div class="product-item mb-5 col-md-3">
                                        <a href="{% url 'product:detail' item.id %}">
                                            <div class="product discount product_filter">
                                                <div class="product_image">
                                                <img src="{{item.imageURL}}" alt="">
                                                </div>
                                                <div class="favorite favorite_left"></div>
                                                <!-- <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>-$20</span></div> -->
                                                <div class="product_info">
                                                <h6 class="product_name">{{item.title}}</h6>
                                                <div class="product_price">Rs{{item.price_after_discount}}<span>Rs{{item.price}}</span></div>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="add_to_cart_button">
                                        <form method='POST' action="{% url 'carts:update' %}">
                                        {% csrf_token %}
                                        <input type="hidden" value="{{ item.id }}" name='products_id'>
                                        <input type='hidden' name='qty' value='1'/>
                                        <button class="btn btn-danger" type="submit" name='add' style="width: 100%;">
                                            Add to cart
                                            <span><i class="fa fa-cart-plus"></i></span>
                                        </button>   
                                        </form>
                                    </div>
                                    </div>
                                {% endfor %}
                            <!-- </div> -->
                            <!-- </div> -->
                        {% else %}
                        <div class="container text-center">
                            <h5>No results found</h5>
                            <p>Try again with different parameters</p>
                        </div>
                        {% endif %}
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/shop_services.html
<section class="shop-services section home">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6 col-12">
          <!-- Start Single Service -->
          <div class="single-service">
            <i class="ti-rocket"></i>
            <h4>Free shiping</h4>
            <p>Orders over Rs1000</p>
          </div>
          <!-- End Single Service -->
        </div>
        <div class="col-lg-3 col-md-6 col-12">
          <!-- Start Single Service -->
          <div class="single-service">
            <i class="ti-reload"></i>
            <h4>Free Return</h4>
            <p>Within 30 days returns</p>
          </div>
          <!-- End Single Service -->
        </div>
        <div class="col-lg-3 col-md-6 col-12">
          <!-- Start Single Service -->
          <div class="single-service">
            <i class="ti-lock"></i>
            <h4>Secure Payment</h4>
            <p>100% secure payment</p>
          </div>
          <!-- End Single Service -->
        </div>
        <div class="col-lg-3 col-md-6 col-12">
          <!-- Start Single Service -->
          <div class="single-service">
            <i class="ti-tag"></i>
            <h4>Best Piece</h4>
            <p>Guaranteed price</p>
          </div>
          <!-- End Single Service -->
        </div>
      </div>
    </div>
  </section>

templates/sliders.html
<div id="home_main_slider" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner" role="listbox" style="width: 100%;">
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://images.unsplash.com/photo-1488459716781-31db52582fe9?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80"
        alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src=https://images.unsplash.com/photo-1563746098251-d35aef196e83?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1955&q=80"
        alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://images.unsplash.com/photo-1550828520-4cb496926fc9?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2090&q=80"
        alt="Third slide">
    </div>
  </div>

  <a class="carousel-control-prev" href="#home_main_slider" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#home_main_slider" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>