blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, create_comment


app_name='blog'

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('detail/<str:pk>', BlogDetailView.as_view(), name="detail"),
    path('comment', create_comment, name='comment'),
]

carts/urls.py
from django.urls import path
from .views import cart_home, update_cart


app_name = 'carts'

urlpatterns = [
    path('', cart_home, name='home'),
    path('update', update_cart, name='update'),
]

customer/urls.py
from django.urls import path
from .views import *

app_name = 'customer'

urlpatterns = [
    path('', CustomerProfileView.as_view(), name='home'),
    path('register-customer', RegisterCustomerView.as_view(), name='register'),
    path('edit-customer', customer_profile_edit, name='edit'), 
    path('confirm', registration_confirmation, name='confirm'),
    path('settings', CustomerSettingsView.as_view(), name='setting'),
    path('delete-account', customer_delete, name='delete_account'),
    path('subscribe_newsletter', subscribe_newsletter, name='subscribe_newsletter'),
    path('contact_us', TemplateView.as_view(template_name='contact_us.html'), name='contact_us'),
    path('contact_us_ajax', contact_us_view, name='contact_us_ajax'),
]

product/urls.py
from django.urls import path
from .views import (organicstoreListView, organic_station_detail, shop_page_view, CreateProductView,
    product_detail, ProductUpdateView, ProductDeleteView, SupplierProductsListView,
    create_comment, ProductSearchResultView, rate_product, CategoryProductView)


app_name = 'product'

urlpatterns = [
    path('organic-store', organicstoreListView.as_view(), name='organic_station'),
    path('organic-detail/<str:pk>', organic_station_detail, name='organic_detail'),
    path('shop', shop_page_view, name='shop_page'),
    path('create', CreateProductView.as_view(), name='create'),
    path('detail/<str:pk>', product_detail, name='detail'),
    path('update/<str:pk>', ProductUpdateView.as_view(), name='update'),
    path('delete/<str:pk>', ProductDeleteView.as_view(), name='delete'),
    path('all-products/<str:email>', SupplierProductsListView.as_view(), name='all_products'),
    path('comment', create_comment, name='comment'),
    path('search/', ProductSearchResultView.as_view(), name='search'),
    path('rate-product', rate_product, name='rate-product'),
    path('catproduct/<str:pk>', CategoryProductView.as_view(), name='cat-product'),
]

seller/urls.py
from django.urls import path
from .views import SupplierProfileView, supplier_profile_edit, SupplierSettingsView 

app_name = 'seller'

urlpatterns = [
    path('', SupplierProfileView.as_view(), name='home'),
    path('edit-supplier', supplier_profile_edit, name='edit'),
    path('settings', SupplierSettingsView.as_view(), name='setting'),
]

templates/utils/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="container forget-password mt-5">
    <div class="row justify-content-center mt-5">
        <div class="col-md-4 col-md-offset-2 mt-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="text-center">
                        <img src="https://i.ibb.co/rshckyB/car-key.png" alt="car-key" border="0">
                        <h2 class="text-center">Change Password</h2>
                        <p>You can reset your password here.</p>
                        <form id="register-form" role="form" autocomplete="off" class="form" method="post">
                            {% csrf_token %}
                            {{form | crispy }}
                            <div class="form-group">
                                <input name="btnForget" class="btn btn-primary btnForget" value="Save Changes" type="submit">
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
    

templates/utils/create_item.html
{% load crispy_forms_tags %}

      <div class="col-md-10">
          <div class='card'>
              <div class='text-center mt-3'>
                  <strong>{{title}}</strong>  
              </div>
              <div class="card-body">
                  <form action="" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {{form|crispy}}
                      <button class='btn btn-dark' type="submit">Create</button>
                  </form>
              </div>
          </div>
      </div>     

templates/utils/delete_item.html
<div class="container-fluid mt-5">
    <div class="row wow fadeIn">
        <div class="card">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>Are you sure you want to delete this {{title}}<br/><strong>{{object}}</strong>?</h4>
                    <br>
                    <a onclick="history.go(-1)" class="btn btn-success btn-sm">Cancel</a>
                    <button type="submit" class='btn btn-danger btn-sm'>Delete</button>  
                </form>
            </div>
        </div>
    </div>
</div>

templates/utils/hamburger_menu.html
<style>

body
{
  margin: 0;
  padding: 0;
  
  /* make it look decent enough */
  background: #232323;
  color: #cdcdcd;
  font-family: "Avenir Next", "Avenir", sans-serif;
}

#menuToggle
{
  display: block;
  position: relative;
  top: 50px;
  left: 50px;
  
  z-index: 1;
  
  -webkit-user-select: none;
  user-select: none;
}

#menuToggle a
{
  text-decoration: none;
  color: #232323;
  
  transition: color 0.3s ease;
}

#menuToggle a:hover
{
  color: tomato;
}


#menuToggle input
{
  display: block;
  width: 40px;
  height: 32px;
  position: absolute;
  top: -7px;
  left: -5px;
  
  cursor: pointer;
  
  opacity: 0; /* hide this */
  z-index: 2; /* and place it over the hamburger */
  
  -webkit-touch-callout: none;
}

/*
 * Just a quick hamburger
 */
#menuToggle span
{
  display: block;
  width: 33px;
  height: 4px;
  margin-bottom: 5px;
  position: relative;
  
  background: #cdcdcd;
  border-radius: 3px;
  
  z-index: 1;
  
  transform-origin: 4px 0px;
  
  transition: transform 0.5s cubic-bezier(0.77,0.2,0.05,1.0),
              background 0.5s cubic-bezier(0.77,0.2,0.05,1.0),
              opacity 0.55s ease;
}

#menuToggle span:first-child
{
  transform-origin: 0% 0%;
}

#menuToggle span:nth-last-child(2)
{
  transform-origin: 0% 100%;
}

/* 
 * Transform all the slices of hamburger
 * into a crossmark.
 */
#menuToggle input:checked ~ span
{
  opacity: 1;
  transform: rotate(45deg) translate(-2px, -1px);
  background: #232323;
}

/*
 * But let's hide the middle one.
 */
#menuToggle input:checked ~ span:nth-last-child(3)
{
  opacity: 0;
  transform: rotate(0deg) scale(0.2, 0.2);
}

/*
 * Ohyeah and the last one should go the other direction
 */
#menuToggle input:checked ~ span:nth-last-child(2)
{
  transform: rotate(-45deg) translate(0, -1px);
}

/*
 * Make this absolute positioned
 * at the top left of the screen
 */
#menu
{
  position: absolute;
  width: 300px;
  margin: -100px 0 0 -50px;
  padding: 50px;
  padding-top: 125px;
  
  background: #ededed;
  list-style-type: none;
  -webkit-font-smoothing: antialiased;
  /* to stop flickering of text in safari */
  
  transform-origin: 0% 0%;
  transform: translate(-100%, 0);
  
  transition: transform 0.5s cubic-bezier(0.77,0.2,0.05,1.0);
}

#menu li
{
  padding: 10px 0;
  font-size: 22px;
}

/*
 * And let's slide it in from the left
 */
#menuToggle input:checked ~ ul
{
  transform: none;
}   
</style>

<nav role="navigation">
    <div id="menuToggle">
      <!--
      A fake / hidden checkbox is used as click reciever,
      so you can use the :checked selector on it.
      -->
      <input type="checkbox" />
      
      <!--
      Some spans to act as a hamburger.
      
      They are acting like a real hamburger,
      not that McDonalds stuff.
      -->
      <span></span>
      <span></span>
      <span></span>
      
      <!--
      Too bad the menu has to be inside of the button
      but hey, it's pure CSS magic.
      -->
      <ul id="menu">
        <a href="#"><li>Home</li></a>
        <a href="#"><li>About</li></a>
        <a href="#"><li>Info</li></a>
        <a href="#"><li>Contact</li></a>
        <a href="https://erikterwan.com/" target="_blank"><li>Show me more</li></a>
      </ul>
    </div>
  </nav>

templates/utils/login.html
{% extends 'utils/main.html' %}

{% block title %}<title>Login Page</title>{% endblock %}

{% load crispy_forms_tags %}

{% block main %}

    <div class='my-5'></div>

    <div style="background-image: url(../static/img/background.jpg); height: 100vh;">
        <div class="container" style="position: absolute; top: 40%; left: 50%; transform: translate(-50%, -50%);">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-body">
                            <form class="text-center" style="color: #757575;" action="" method="post">
                                {% csrf_token %}
    
                                {{form|crispy}}
    
                                <div class="text-center">
                                    <button type="submit" class="btn btn-outline-orange my-4">Login</button>
                                </div>
                            </form>
                        </div>  
                    </div>
                </div>
            </div>
        </div>
    </div>
       
{% endblock %}

templates/utils/main.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/bootstrap4/bootstrap.min.css' %}">
    <link href="{% static 'coloshop/plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/plugins/OwlCarousel2-2.2.1/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/main_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'coloshop/styles/responsive.css' %} ">

    <!-- Material Design Bootstrap -->
    <!-- <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">   -->
    
    {% block css %}
      
    {% endblock %}

    {% block title %}

    {% endblock %}

  </head>

  <body>

    {% include 'utils/navbar.html' %}
    
    {% block main %}
    {% endblock %}


    <!-- Optional JavaScript -->
    <!-- SCRIPTS -->
    <script src="{% static 'coloshop/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'coloshop/styles/bootstrap4/popper.js' %}"></script>
    <script src="{% static 'coloshop/styles/bootstrap4/bootstrap.min.js' %}"></script>
    <script src="{% static 'coloshop/plugins/Isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'coloshop/plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
    <script src="{% static 'coloshop/plugins/easing/easing.js"></script>
  
    <!-- MDB core JavaScript -->
    <!-- <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script> -->
  
    <!-- Initializations -->
    {% block js %}
    {% endblock %}

    <script type="text/javascript">
      // Animations initialization
      new WOW().init();

    </script>
  </body>
</html>

templates/utils/navbar.html
{% load static %}

<style>
  
  .overlay {
    height: 0%;
    width: 100%;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    overflow-y: hidden;
    transition: 0.5s;
  }

  
  .overlay a {
    padding: 8px;
    text-decoration: none;
    font-size: 36px;
    color: #0f0f0f;
    display: block;
    transition: 0.3s;
  }
  
  .overlay a:hover, .overlay a:focus {
    color:#fc0505;
  }
  
  .overlay .closebtn {
    position: absolute;
    top: 20px;
    right: 45px;
    font-size: 60px;
  }

  .form-control-borderless {
    border: none;
}

.form-control-borderless:hover, .form-control-borderless:active, .form-control-borderless:focus {
    border: none;
    outline: none;
    box-shadow: none;
}
  
</style>

<header class="header trans_300">
  <div class="main_nav_container fixed-top">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-right">

          <div class="logo_container img-fluid">
            <!-- <a href="{% url 'home' %}"><strong>kaii<span style="color: orange;">mart</span></strong></a>  -->
            <a href="{% url 'home' %}"><img src="{% static 'img/KaiiMart.png' %}" class="img-fluid" height="70px" width="70px"  alt="Kaii Mart's Logo"></a> 
          </div>
       
          <nav class="navbar">

            <ul class="navbar_menu mr-3">
              {% if not user.is_manager and not user.is_admin and not user.is_delivery_team %}
              <li><a href="{% url 'product:organic_station' %}">Organic Station</a></li>
              <li><a href="{% url 'product:shop_page' %}">Shop</a></li>
              {% endif %}
              {% if user.is_authenticated and user.supplierprofile %}
              <li><a href="{% url 'product:create' %}">Add Product</a></li>
              {% endif %}
              {% if not user.is_manager and not user.is_admin and not user.is_delivery_team %}
              <li>
                <form class="form-inline ml-5 mr-3" action="{% url 'product:search' %}" method="get">
                  <input class="form-control search w-150" type="text" name='q' placeholder="Search" aria-label="Search">
                </form>
              </li>
              {% endif %}
            </ul>

            <ul class="navbar_user">
              {% if user.is_anonymous %}
              <li><a href="{% url 'login' %}"><i class="fa fa-user" aria-hidden="true"></i></a></li>
              {% elif user.is_customer %}
              <li class="nav-item avatar dropdown">  
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-55" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false"> 
                {% if user.customerprofile.imageURL %}
                <img src="{{user.customerprofile.imageURL}}" class="rounded-circle z-depth-0"
                alt="avatar" height="25" width='25'>
                {% else %}
                <i class="fa fa-user mr-1"></i>{{user.username}}
                {% endif %}  
                </a>
                <div class="dropdown-menu dropdown-menu-lg-right dropdown-secondary text-center"
                  aria-labelledby="navbarDropdownMenuLink-55">
                    <a href="{% url 'customer:home' %}">Profile</a>
                    <a href="{% url 'customer:setting' %}">Settings</a>
                    <a href="{% url 'logout' %}">Logout</a>
                </div>
              </li>
              {% elif user.is_supplier %}
              <li class="nav-item avatar dropdown">  
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-55" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                {% if user.supplierprofile.imageURL %}
                <img src="{{user.supplierprofile.imageURL}}" class="rounded-circle z-depth-0"
                alt="avatar" height="25" width='25'>
                {% else %}
                <i class="fa fa-user mr-1"></i>{{user.username}}
                {% endif %}  
                </a>
                <div class="dropdown-menu dropdown-menu-lg-right dropdown-secondary text-center"
                  aria-labelledby="navbarDropdownMenuLink-55">
                  <a href="{% url 'seller:home' %}">Profile</a>
                  <a href="{% url 'product:all_products' email=user %}">My Products</a>
                  <a href="{% url 'seller:setting' %}">Settings</a>
                  <a href="{% url 'logout' %}">Logout</a>
                </div>
              </li>
              {% endif %}

              {% if user.is_supplier or user.is_customer or user.is_anonymous %}
              <li class="checkout ml-4">
                <a href="{% url 'carts:home' %}">
                  <i class="fa fa-shopping-cart p-3 py-5" aria-hidden="true"></i>
                  <span id="checkout_items" class="checkout_items">2</span>
                  {% if request.session.items_total %}
                  <span id="checkout_items" class="checkout_items"> {{request.session.items_total}}</span>
                  {% else %}
                  <span id="checkout_items" class="checkout_items">0</span>
                  {% endif %} 
                </a>
              </li>
              {% endif %}
            </ul>

            <ul class="nav justify-content-end ml-5">
              <li class="nav-item">
                <span style="font-size:30px; cursor:pointer"  onclick="openNav()">&#9776;</span>
          
              </li>
              
            </ul>

            

          </nav>

          <div id="myNav" class="hamburger_menu overlay">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">
              <div class="hamburger_close"><i class="fa fa-times" aria-hidden="true"></i></div>
            </a>
              <div class="hamburger_menu_content text-center my-5">

                <ul class="menu_top_nav">
                  <li class="mb-3">
                    <!-- <form class="form-inline ml-5" action="{% url 'product:search' %}" method="get">
                      <input class="form-control search" type="text" name='q' placeholder="Search" aria-label="Search">
                    </form> -->

                    <div class="row justify-content-center">
                      <div class="col-12 col-md-10 col-lg-8">
                          <form class="card card-sm" action="{% url 'product:search' %}" method="get">
                              <div class="card-body row no-gutters align-items-center">
                                  <div class="col-auto">
                                      <i class="fa fa-search h4 text-body"></i>
                                  </div>
                                  <div class="col">
                                      <input class="form-control form-control-lg form-control-borderless" type="text" name='q' type="search" placeholder="Search for fruits or vegetables">
                                  </div>
                                  <div class="col-auto">
                                      <button class="btn btn-lg btn-warning" type="submit">Search</button>
                                  </div>
                              </div>
                          </form>
                      </div>
                  </div>
                  </li>
                    
                  <li class=" mt-2"><a href="{% url 'home' %}">Home <i class="fa fa-home ml-2"></i></a></li>
                  <li class="mt-2"><a href="{% url 'product:organic_station' %}">Organic Station<i class="fa fa-shopping-basket ml-2"></i></a></li>
                  <li class=" mt-2"><a href="{% url 'product:shop_page' %}">Shop<i class="fa fa-shopping-cart ml-2"></i></a></li>
                  <li class=" mt-2"><a href="{% url 'blog:home' %}">Blog<i class="fa fa-newspaper-o ml-2"></i></a></li>
                  <li class=" mt-2"><a href="{% url 'customer:contact_us' %}">Contact<i class="fa fa-address-book ml-2"></i></a></li>
                  
                  {% if user.is_authenticated and user.supplierprofile %}
                  <li class="mt-2"><a href="{% url 'product:create' %}">Add Product<i class="fa fa-plus-square ml-2" aria-hidden="true"></i></a></li>
                  {% endif %}
          
                  {% if user.is_anonymous %} 
                  <li class="mt-2">
                    <a href="{% url 'login' %}">LogIn<i class="fa fa-sign-in ml-2" aria-hidden="true"></i></a>
                  </li>
                  <li class="mt-2">
                    <a href="{% url 'customer:register' %}">
                      Register<i class="fa fa-user-plus ml-2" aria-hidden="true"></i>
                    </a>
                  </li>
                  {% else %}
                  <li class="mt-2"><a href="{% url 'logout' %}">Logout<i class="fa fa-sign-out ml-2" aria-hidden="true"></i></a></li>
                  {% endif %}
                </ul>

              </div>
            </div>
          </div

        </div>
      </div>  
    </div>
  </div>
</header>

<script>
  function openNav() {
    document.getElementById("myNav").style.height = "100%";
  }
  
  function closeNav() {
    document.getElementById("myNav").style.height = "0%";
  }
  </script>

templates/utils/otp_form.html
{% extends 'utils/main.html' %}

{% block title %}<title>Login Page</title>{% endblock %}


{% block main %}

    <div class="mt-5"></div>

    <div class="container" style="margin-top: 150px;">
        <header>
            <span class="display-4">Account Confirmation</span>
        </header>
        <hr>
        <span>Please enter the OTP code you just recieved.</span>
        <div class="d-flex justify-content-center">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'customer:confirm' %}" method="post">
                        {% csrf_token %}
                        <input type="text" name='otp'>
                        <button class='btn btn-info' type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/utils/password_change_done.html
{% extends 'base.html' %}


{% block main %}
    <div class="container mt-5 mb-5">
        <div class="mt-5 mb-5">Congratulations</div>
        <div class="mt-5 text-center ml-5">
        <header class="mt-5 ml-5 mb-5">
            <span class="display-4 mt-5 py-5 ml-5">Password Successfully Changed</span>
        </header>
        <hr>
        <div class="homebutton mt-5">
            <a href="{% url 'home' %}" class="btn btn-secondary">Take me Home</a>
        </div>
        </div>
    </div>
{% endblock main %}
    

templates/utils/register.html
{% extends 'utils/main.html' %}

{% block title %}<title>Register Customer</title>{% endblock %}
{% load crispy_forms_tags%}

{% block main %}

    <div class="mt-5"></div>

    <div style="background-image: url(../static/img/background.jpg); height: 100vh;">
        <div class="container" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="text-center text-danger mt-3">
                            Register as Customer
                        </div>
                        <div class="card-body">
                            <form class="text-center" style="color: #757575;" action="" method="post">
                                {% csrf_token %}
    
                                {{form|crispy}}
    
                                <div class="text-center">
                                    <button type="submit" class="btn btn-outline-orange my-4">SignUp</button>
                                </div>

                                <p>Already member?
                                    <a href="{% url 'login' %}">Login</a>
                                </p>

                                <p>By clicking
                                    <em>Sign up</em> you agree to our
                                    <a href="" target="_blank">terms of service</a>
                                </p>
                            </form>
                        </div>  
                    </div>
                </div>
            </div>
        </div>
    </div>
     
{% endblock %}

templates/utils/settings.html
{% extends 'base.html' %}

{% block title %}<title>Settings</title>{% endblock %}


{% block main %}
    <div class="container">
        <div>
            <strong>Change Password</strong>
            <a href="{% url 'password_change' %}"></a>
        </div>
        <div>
            <strong>Delete Account</strong>
            <a href=""></a>
        </div>

    </div>

{% endblock %}

templates/utils/update_item.html
{% load crispy_forms_tags %}

<div class="container-fluid mt-5">
    <div class="row wow fadeIn">
      <div class="col-md-10">
          <div class='card'>
              <div class='text-center mt-3'>
                  <strong>{{title}}</strong>  
              </div>
              <div class="card-body">
                  <form action="" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {{form|crispy}}
                      <button class='btn btn-dark' type="submit">Update</button>
                  </form>
              </div>
          </div>
      </div>
    </div>
  </div>   